### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**
1.x match latest stable go version

### CODE REVIEW

**Comment by campoy** [comment]
trying to start travis-ci ...

**Comment by dvrkps** [comment]
@campoy go get fails for some reason... "The command "go get -v -t ./..." failed and exited with 1 during ."

**Comment by campoy** [comment]
This repo is still not ready for contributions, sorry.

**Comment by dvrkps** [comment]
@campoy np. Cheers.

**Pull request closed without merging**
